//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Lucy.Document
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public static class DiscoveryProvider
	{
		public static IDiscovery GetDiscovery(string uri)
		{
            return new ParallelFolderDiscovery();
		}

	}
}

