//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Lucy.Document
{
    using Lucy.Core;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// Define a behavior of document location discovery.
    /// The aim of the discovery is to identify all individual document
    /// </summary>
	public interface IDiscovery 
	{
        ICollection<DocumentIdentity> Discover(DocumentLocation location);

	}
}

