//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Lucy.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// States of discovery workflow
	/// </summary>
	public enum DiscoveryStates : int
	{
		/// <summary>
		/// State unkwnow
		/// </summary>
		Undefined = 0,
		/// <summary>
		/// Still exploring
		/// </summary>
		Exploring,
		/// <summary>
		/// Exploring occured once
		/// </summary>
		Explored,
        /// <summary>
        /// Exploring never occured
        /// </summary>
        NotExplored
	}
}
