//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Lucy.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// Write messages in the log buffer
	/// </summary>
	public interface ILogger 
	{
		/// <summary>
		/// Write an informational message
		/// </summary>
		/// <param name="message">Message to write</param>
		void Info(string message);

		/// <summary>
		/// Write an warning message
		/// </summary>
		/// <param name="message">Message to write</param>
		void Waring(string message);

		/// <summary>
		/// Write an error
		/// </summary>
		/// <param name="message">Error message </param>
		void Error(string message);

		/// <summary>
		/// Write a message from an Exception
		/// </summary>
		/// <param name="ex">Exception  to log</param>
		void Error(Exception ex);

		/// <summary>
		/// Write a debug information
		/// </summary>
		void Debug(string message);

	}
}

