//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Lucy.Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    /// <summary>
    /// States of indexations
    /// </summary>
	public enum IndexationStates : int
	{
        /// <summary>
        /// Don't know
        /// </summary>
		Undefined = 0,
		/// <summary>
		/// Indexing in progress 
		/// </summary>
        Indexing,
        /// <summary>
        /// document indexed at least once
        /// </summary>
		Indexed,
        /// <summary>
        /// document never indexed
        /// </summary>
		NotIndexed,
	}
}
