//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil
//     Les modifications apportées à ce fichier seront perdues si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Lucy.Extensibility
{
	using Lucy.Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;


	/// <summary>
	/// Define the behavior of an document Parser
	/// </summary>
	public interface IParser 
	{
		/// <summary>
		/// Friendly name of the parser
		/// </summary>
		string Name { get;}

		/// <summary>
		/// Array of supported file extension
		/// </summary>
		IEnumerable<string> SupportedFileExtensions { get;  }

		/// <summary>
		/// Parse an document into chuck and set the documentID
		/// </summary>
		IEnumerable<DocumentChunk> Parse(DocumentIdentity document);

	}
}

